id: P010361
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:45:55.642223
source_metadata:
  id: bdr:W1KG8471
  title: ཕན་བདེའི་འཇུག་ངོགས།
  author: ''
  volumes:
    41975ad6ec074cec839b014ea93e4227:
      image_group_id: I1KG8509
      title: ''
      volume_number: 1
      total_pages: 256
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
